redhat-et/copilot-ops

- data-lab/README.md
- data-lab/openshiftai.ipynb
- data-lab/requirements.txt
Signed-off-by: Oleg Silkin <16809287+osilkin98@users.noreply.github.com>
> Create sandbox directory for working with data

- .vscode/settings.json
- pkg/cmd/filemap.go
- pkg/cmd/types.go
- pkg/errors/errors.go
- pkg/filemap/filemap.go
- pkg/openai/edit.go
- pkg/openai/types.go
- pkg/tests/test_suite.go
This PR creates the base packages and types for the project.
> Create copilot-ops CLI skeleton

- pkg/filemap/filemap.go
- pkg/openai/edit.go
- pkg/openai/openai.go
- pkg/openai/test.go
- pkg/openai/types.go
This PR implements the necessary methods to communicate with the OpenAI API, encode and decode to and from files.
> Adds OpenAI methods, encoding, decoding

- pkg/cmd/patch.go
> Fix patch command to use CreateOpenAIClient

- .github/workflows/ci.yaml
> Add CI workflow that builds, tests, and upload artifacts

- README.md
- examples/aws-credentials-secret.yaml
- pkg/cmd/generate.go
This PR generates the prompt for `generate` dynamically depending on whether or not any files were included.
> Generate prompt is formatted dynamically

- .github/workflows/ci.yaml
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
> Pull OpenAI Envs From Repository Secrets

- .github/workflows/ci.yaml
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
> set default shell to bash

- README.md
This PR updates the `README.md` to document `--write` and `--fileset` arguments. 
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
> document --write & --fileset

- .github/workflows/bot.yaml
> Fixes #28 add issues bot workflow

- .github/workflows/bot.yaml
> fix bot build to actually make a binary, and add cache for go mods

- .github/workflows/bot.yaml
> bot: try to fix extracting the command

- .github/workflows/bot.yaml
> bot: use github-script to parse

- .github/workflows/bot.yaml
> bot: fix script

- .github/workflows/bot.yaml
> bot: fix script again

- .github/workflows/bot.yaml
- .github/workflows/ci.yaml
> bot: fix createComment

- .github/workflows/bot.yaml
> bot: fix the fix

- .github/workflows/bot.yaml
- .github/workflows/ci.yaml
> bot: fix ** 10

- .github/workflows/bot.yaml
> bot: fix logging

- .github/workflows/bot.yaml
> bot: debugging

- .github/workflows/bot.yaml
> bot: reply exitCode,stdout,stderr on error too

- README.md
> fix env name

- pkg/cmd/constants.go
- pkg/cmd/edit.go
- pkg/cmd/generate.go
- pkg/cmd/types.go
- pkg/cmd/utils.go
- pkg/filemap/filemap.go
- pkg/filemap/types.go
- pkg/openai/types.go
This PR introduces basic output formatting, allowing the user to specify json or plain output.
> Output formatting

- .golangci.yaml
This should close #89 
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
> Update golangci-lint.yaml to v1.47.3

- Dockerfile
> install git in the dockerfile
